server:
  port: 80

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/mongoega
  mail:
    host: smtp.gmail.com
    port: 587
    username: test
    password: test
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

